global:
  imagePullPolicy: IfNotPresent # empty pull policy means k8s default is used ("always" if tag == ":latest", "ifnotpresent" else)
# Dependency charts
etcd:
  persistentVolume:
    enabled: true
    storage: 1Gi
  replicas: 3 # How many instances of etcd will be added to the initial cluster.
  resources: # resource requirements for etcd containers
    limits:
      cpu: 100m
      memory: 100Mi
  image:
    repository: daocloud.io/piraeus/etcd
    tag: v3.4.9
csi-snapshotter:
  enabled: true # <- enable to add k8s snapshotting CRDs and controller. Needed for CSI snapshotting
  image: daocloud.io/piraeus/snapshot-controller:v2.1.0
  replicas: 3
  resources: # resource requirements for the cluster snapshot controller.
    limits:
      cpu: 100m
      memory: 100Mi
stork:
  enabled: true
  storkImage: daocloud.io/piraeus/stork:latest
  schedulerImage: daocloud.io/piraeus/kube-scheduler-amd64
  schedulerTag: ""
  replicas: 3
  storkResources: # resources requirements for the stork plugin containers
    limits:
      cpu: 100m
      memory: 100Mi
  schedulerResources: # resource requirements for the kube-scheduler containers
    limits:
      cpu: 100m
      memory: 100Mi
csi:
  enabled: true
  pluginImage: daocloud.io/piraeus/piraeus-csi:v0.9.0
  csiAttacherImage: daocloud.io/piraeus/csi-attacher:v2.2.0
  csiNodeDriverRegistrarImage: daocloud.io/piraeus/csi-node-driver-registrar:v1.3.0
  csiProvisionerImage: daocloud.io/piraeus/csi-provisioner:v1.6.0
  csiSnapshotterImage: daocloud.io/piraeus/csi-snapshotter:v2.1.0
  csiResizerImage: daocloud.io/piraeus/csi-resizer:v0.5.0
  controllerReplicas: 3
  nodeAffinity: {}
  nodeTolerations: []
  controllerAffinity: {}
  controllerTolerations: []
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
priorityClassName: ""
drbdRepoCred: drbdiocred # <- Specify the kubernetes secret name here
linstorHttpsControllerSecret: "" # <- name of secret containing linstor server certificates+key. See docs/security.md
linstorHttpsClientSecret: "" # <- name of secret containing linstor client certificates+key. See docs/security.md
operator:
  replicas: 3 # <- number of replicas for the operator deployment
  image: daocloud.io/piraeus/piraeus-operator:v1.0.0
  resources:
    limits:
      cpu: 100m
      memory: 100Mi
  controller:
    controllerImage: daocloud.io/piraeus/piraeus-server:v1.7.3
    luksSecret: ""
    dbCertSecret: ""
    dbUseClientCert: false
    sslSecret: ""
    affinity: {}
    tolerations: []
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
  satelliteSet:
    satelliteImage: daocloud.io/piraeus/piraeus-server:v1.7.3
    storagePools: null
    sslSecret: ""
    automaticStorageType: None
    affinity: {}
    tolerations: []
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
    # kernelModuleInjectionImage: daocloud.io/piraeus/drbd9-bionic:v9.0.24
    kernelModuleInjectionImage: daocloud.io/piraeus/drbd9-centos7:v9.0.24
    kernelModuleInjectionMode: Compile
    kernelModuleInjectionResources:
      limits:
        cpu: 200m
        memory: 200Mi
